# Generated by Django 5.2 on 2025-04-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operadoras", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operadora",
            options={"managed": False},
        ),
    ]
